# -*- mode: ruby -*-
# vi: set ft=ruby :

LOCAL_USER = ENV['USER']
USER_SERVER = ENV['USER'] + "S"
USER_SERVERW = ENV['USER'] + "SW"
print "server is : #{USER_SERVER}\n"
print "server worker is : #{USER_SERVERW}\n"

Vagrant.configure("2") do | config |
    config.vm.box = "ubuntu/jammy64"
    
    config.vm.define "#{USER_SERVER}" do |server|
        server.vm.hostname = "#{USER_SERVER}"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "virtualbox" do |vb|
            vb.name = "#{USER_SERVER}"
            vb.gui = true
            vb.memory = "1024"
            vb.cpus = "1"
        end
        server.vm.provision "shell", privileged: true, path: "scripts/server.sh"
        server.vm.provision "shell", privileged: true, <<-SHELL
            kubectl apply -f app1.yaml -f app2.yaml -f app3.yaml -f ingress.yaml
        SHELL
    end