ntp_servers:
  - "10.15.3.246"

vault_cert: 

  - owner: "prometheus"
    group: "prometheus"
    base_path: "/etc/prometheus_ssl/"
    issue_path: "rd/pki/monitoring/sign/services"
    common_name: "prometheus.com"
    cert_path: "prometheus.crt"
    key_path: "prometheus.key"
    ip_sans: 
      - "{{ ansible_host }}"
      - "{{ prometheus_private_ip }}"
      - "127.0.0.1"
    alt_names: "localhost"
    # force_renew: true

  - owner: "prometheus"
    group: "prometheus"
    base_path: "/etc/prometheus_ssl_client/"
    issue_path: "rd/pki/monitoring/sign/clients"
    common_name: "prometheusclient"
    cert_path: "prometheus_client.crt"
    key_path: "prometheus_client.key"
    # force_renew: true

  - owner: "prometheus"
    group: "prometheus"
    base_path: "/etc/prometheus_ssl/"
    issue_path: "rd/pki/monitoring/sign/services"
    common_name: "sidecarA.com"
    cert_path: "sidecarA.crt"
    key_path: "sidecarA.key"
    ip_sans: 
      - "{{ ansible_host }}"
      - "{{ prometheus_private_ip }}"
      - "127.0.0.1"
    alt_names: "localhost"
    # force_renew: true

  - owner: "prometheus"
    group: "prometheus"
    base_path: "/etc/prometheus_ssl_client/"
    issue_path: "rd/pki/monitoring/sign/clients"
    common_name: "sidecarA"
    cert_path: "sidecarA.crt"
    key_path: "sidecarA.key"
    # force_renew: true

  - owner: "node_exporter"
    group: "node_exporter"
    base_path: "/etc/node_exporter_ssl/"
    issue_path: "rd/pki/monitoring/sign/services"
    common_name: "nodeexporterprometheus.com"
    cert_path: "node_exporter.crt"
    key_path: "node_exporter.key"
    ip_sans: 
      - "{{ ansible_host }}"
      - "{{ prometheus_private_ip }}"
    # force_renew: true