ntp_servers:
  - "10.15.3.246"

vault_cert:

  - owner: "thanos"
    group: "thanos"
    base_path: "/etc/thanos_ssl_http/"
    issue_path: "rd/pki/monitoring/sign/services"
    common_name: "thanosquery.com"
    cert_path: "thanos.crt"
    key_path: "thanos.key"
    ip_sans: "{{ ansible_host }}, {{ thanos_query_private_ip }}, {{ keepalived_query }}"
    alt_names: "localhost"
    # force_renew: true

  - owner: "thanos"
    group: "thanos"
    base_path: "/etc/thanos_ssl_client_http/"
    issue_path: "rd/pki/monitoring/sign/clients"
    common_name: "thanosqueryclient"
    cert_path: "thanos.crt"
    key_path: "thanos.key"
    # force_renew: true

  - owner: "thanos"
    group: "thanos"
    base_path: "/etc/thanos_ssl_grpc/"
    issue_path: "rd/pki/monitoring/sign/services"
    common_name: "thanosquerygrpc.com"
    cert_path: "thanos.crt"
    key_path: "thanos.key"
    ip_sans: "{{ ansible_host }}, {{ thanos_query_private_ip }}, {{ keepalived_query }}"
    alt_names: "localhost"
    # force_renew: true

  - owner: "thanos"
    group: "thanos"
    base_path: "/etc/thanos_ssl_client_grpc/"
    issue_path: "rd/pki/monitoring/sign/clients"
    common_name: "thanosqueryclientgrpc"
    cert_path: "thanos.crt"
    key_path: "thanos.key"
    # force_renew: true

  - owner: "node_exporter"
    group: "node_exporter"
    base_path: "/etc/node_exporter_ssl/"
    issue_path: "rd/pki/monitoring/sign/services"
    common_name: "nodeexporterthanosquery.com"
    cert_path: "node_exporter.crt"
    key_path: "node_exporter.key"
    ip_sans: 
      - "{{ ansible_host }}"
      - "{{ thanos_query_private_ip }}"
    # force_renew: true
    