#SPDX-License-Identifier: MIT-0
---
# tasks file for install_node_exporter

- block:
    - name: "Installing node_exporter"
      include_tasks: install.yml

    - name: "Configuring and deploying node_exporter"
      include_tasks: config.yml
  when: node_exporter_enabled | bool

- name: "Remove node_exporter"
  include_tasks: remove.yml
  when: not (node_exporter_enabled | bool)