# -*- mode: ruby -*-
# vi: set ft=ruby :

# name: wnaseeve
# pswd: wnaseeve

LOCAL_USER = ENV['USER']
print "Local user: #{LOCAL_USER}\n"
ENV['VAGRANT_HOME'] = "/mnt/nfs/homes/wnaseeve/sgoinfre"

Vagrant.configure("2") do |config|
    # Define the box to be used
    config.vm.box = "ubuntu/bionic64"
    # Define the provider (virtualbox, aws, etc)
    config.vm.provider "virtualbox" do |vb|
      vb.name = "#{LOCAL_USER}"
      vb.gui = true
      vb.customize ["modifyvm", :id, "--name", "#{LOCAL_USER}"]
      vb.customize ["setproperty", "machinefolder", "/mnt/nfs/homes/wnaseeve/sgoinfre/#{LOCAL_USER}"]
      vb.memory = "4096"
      vb.cpus = "4"
    end

    # Script to install components
    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        # Basic installation
        apt-get update
        apt-get upgrade -y
        apt install -y sudo
        apt-get install -y git vim make wget curl openssh-server ufw
        apt-get install -y build-essential
        DEBIAN_FRONTEND=noninteractive apt-get install -y ubuntu-desktop
        apt-get install -y virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
        # Install Docker
        curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh    
    SHELL

    config.vm.provision "shell", inline: "sudo adduser #{LOCAL_USER} <<EOF
    wnaseeve
    wnaseeve
    EOF"

    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        # Users & groups
        usermod -aG sudo "#{LOCAL_USER}"
        usermod -aG docker "#{LOCAL_USER}"
        echo "127.0.0.1 "#{LOCAL_USER}".42.fr" >> /etc/hosts/
        hostnamectl set-hostname $USERNAME

        # Sudoers file
        echo "wnaseeve ALL=(ALL) ALL" | sudo tee -a /etc/sudoers

        # Firewall
        sudo ufw allow OpenSSH
        sudo ufw allow 443
        ufw enable
    SHELL

    config.vm.provision "shell", inline: <<-SHELL
        # Install Oh-My-Zsh
        sudo apt-get install -y zsh
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        
        # git clone my project for my repo
        git clone https://github.com/waseemnaseeven/42_CURSUS.git

        

    SHELL
    

    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        # Install Brave Browser
        curl -fsSLo brave.deb https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add brave.deb
        echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" > /etc/apt/sources.list.d/brave-browser-release.list
        apt-get update
        apt-get install -y brave-browser

        # Install VSCode
        curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
        apt-get update
        apt-get install -y code

        # Remove installation files and reboot
        shutdown -r now
    SHELL


end
