#SPDX-License-Identifier: MIT-0
---
# handlers file for install_thanos_compactor
- name: Restart compactor
  systemd:
    name: compactor.service
    state: restarted
    enabled: yes
    daemon_reload: yes
