- name: Check if service exist
  stat:
    path: "{{ prometheus_service_file }}"
  register: service_file

- name: Check if binary exist
  stat:
    path: "{{ prometheus_binary }}"
  register: binary_file

- name: Check if config exist
  stat:
    path: "{{ prometheus_install_dir }}"
  register: config_folder

- name: Check if thanos service exist
  stat:
    path: "{{ prometheus_sidecar_service_file }}"
  register: sidecar_service_file

- name: Check if thanos binary exist
  stat:
    path: "{{ prometheus_sidecar_binary }}"
  register: sidecar_binary_file

- name: Check if thanos config exist
  stat:
    path: "{{ prometheus_sidecar_install_dir }}"
  register: sidecar_config_folder

- name: Check if ssl_server exist
  stat:
    path: "/etc/prometheus_ssl"
  register: ssl_server

- name: Check if ssl_client exist
  stat:
    path: "/etc/prometheus_ssl_client"
  register: ssl_client

- name: Check if ssl_server sidecar exist
  stat:
    path: "/etc/thanos_ssl"
  register: sidecar_ssl_server

- name: Check if ssl_client sidecar exist
  stat:
    path: "/etc/thanos_ssl_client"
  register: sidecar_ssl_client

- name: Disable prom service
  ansible.builtin.systemd_service:
    state: "stopped"
    name: prometheus.service
    enabled: false
  when: service_file.stat.exists

- name: Remove service
  ansible.builtin.file:
    path: "{{ prometheus_service_file }}"
    state: absent
  when: service_file.stat.exists

- name: "Remove prometheus config folder"
  ansible.builtin.file:
    path: "{{ prometheus_install_dir }}"
    state: absent
  when: config_folder.stat.exists

- name: Remove prom binary
  ansible.builtin.file:
    path: "{{ prometheus_binary }}"
    state: absent
  when: binary_file.stat.exists

- name: Remove ssl prom
  ansible.builtin.file:
    path: "/etc/prometheus_ssl"
    state: absent
  when: ssl_server.stat.exists

- name: Remove ssl client prom
  ansible.builtin.file:
    path: "/etc/prometheus_ssl_client"
    state: absent
  when: ssl_client.stat.exists

- name: Disable sidecar service
  ansible.builtin.systemd_service:
    state: "stopped"
    name: sidecar.service
    enabled: false
  when: sidecar_service_file.stat.exists

- name: Remove sidecar service
  ansible.builtin.file:
    path: "{{ prometheus_sidecar_service_file }}"
    state: absent
  when: sidecar_service_file.stat.exists

- name: "Remove sidecar config folder"
  ansible.builtin.file:
    path: "{{ prometheus_sidecar_install_dir }}"
    state: absent
  when: sidecar_config_folder.stat.exists

- name: Remove sidecar binary
  ansible.builtin.file:
    path: "{{ prometheus_sidecar_binary }}"
    state: absent
  when: sidecar_binary_file.stat.exists

- name: Remove ssl sidecar
  ansible.builtin.file:
    path: "/etc/thanos_ssl"
    state: absent
  when: sidecar_ssl_server.stat.exists

- name: Remove ssl client sidecar
  ansible.builtin.file:
    path: "/etc/thanos_ssl_client"
    state: absent
  when: sidecar_ssl_client.stat.exists

- name: Remove user 
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    state: absent
    remove: yes

- name: Remove group
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    state: absent

- name: Refresh systemd
  ansible.builtin.systemd_service:
    daemon_reload: yes
