#SPDX-License-Identifier: MIT-0
---
# handlers file for keepalived
- name: Restart keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
    enabled: yes
    daemon_reload: yes