- name: Copy ca-cert 
  ansible.builtin.copy:
    content: "{{ lookup('pipe', 'vault read -field=certificate rd/pki/monitoring/cert/ca') }}"
    dest: "{{ thanos_ca_file }}"
    owner: "{{ thanos_user }}"
    group: "{{ thanos_group }}"
    mode: '0644'

- name: Create data directory to store metric locally
  ansible.builtin.file:
    path: "{{ thanos_data_dir }}"
    owner: "{{ thanos_user }}"
    group: "{{ thanos_group }}"
    recurse: yes

- name: Deploy bucket config file (bucket.yml) 
  ansible.builtin.template:
    src: bucket.yml.j2
    dest: "{{ thanos_bucket_file }}"
    owner: "{{ thanos_user }}"
    group: "{{ thanos_group }}"
    mode: '0644'

- name: Deploy the tls config file (tls_config.yml) 
  ansible.builtin.template:
    src: tls_config.yml.j2
    dest: "{{ thanos_install_dir }}/tls_config.yml"
    owner: "{{ thanos_user }}"
    group: "{{ thanos_group }}"
    mode: '0644'

- name: Deploying the store systemd service 
  ansible.builtin.template:
    src: store.service.j2
    dest: "{{ thanos_store_service_file }}"
    mode: '0644'

- name: Launch and activate the systemd service
  ansible.builtin.systemd_service:
    name: store.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  notify:
    - Restart store