replicaCount: 1
image:
  tag: 8.6.3
elasticsearch:
  hosts: "http://elasticsearch-master.logging.svc.cluster.local:9200"
service:
  type: NodePort
  nodePort: 30001
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
