replicaCount: 1
image:
  tag: "8.6.3"
logstashPipeline:
  logstash.conf: |
    input { beats { port => 5044 } }
    output { elasticsearch { hosts => ["elasticsearch-master.logging.svc.cluster.local:9200"] } }
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
