#SPDX-License-Identifier: MIT-0
---
# tasks file for keepalived
- name: Ensure Keepalived installed
  ansible.builtin.apt:
    name: keepalived
    state: present
    update_cache: yes

- name: Copy checkthanos script
  ansible.builtin.copy:
    src: checkthanos.sh
    dest: "{{ keepalived_script }}"
    owner: "root"
    group: "root"
    mode: 0755 

- name: Deploy keepalived.conf 
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_install_dir }}/keepalived.conf"
    owner: root
    group: root
    mode: 0644

- name: Launch keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
    enabled: yes
    daemon_reload: yes
    force: false
  notify:
    - Restart keepalived