#SPDX-License-Identifier: MIT-0
---
# tasks file for install_blackbox
- block:
    - name: "Install blackbox"
      include_tasks: install.yml

    - name: "Deploying config file for blackbox"
      include_tasks: config.yml
  when: blackbox_enabled | bool

- name: "Remove blackbox"
  include_tasks: remove.yml
  when: not (blackbox_enabled | bool)