- name: Check if service exist
  stat:
    path: "{{ alertmanager_service_file }}"
  register: service_file

- name: Check if binary exist
  stat:
    path: "{{ alertmanager_binary }}"
  register: binary_file

- name: Check if config exist
  stat:
    path: "{{ alertmanager_install_dir }}"
  register: config_folder

- name: Check if storage exist
  stat:
    path: "{{ alertmanager_storage_path }}"
  register: data_file

- name: Check if ssl_folder exist
  stat:
    path: "/etc/alertmanager_ssl"
  register: ssl_folder

- name: Check if ssl_client exist
  stat:
    path: "/etc/alertmanager_ssl_client"
  register: ssl_client

- name: Disable service
  ansible.builtin.systemd_service:
    state: "stopped"
    name: alertmanager
    enabled: false
  when: service_file.stat.exists

- name: Remove service
  ansible.builtin.file:
    path: "{{ alertmanager_service_file }}"
    state: absent
  when: service_file.stat.exists

- name: Refresh systemd
  ansible.builtin.systemd_service:
    daemon_reload: yes
  when: service_file.stat.exists

- name: "Remove alertmanager config folder"
  ansible.builtin.file:
    path: "{{ alertmanager_install_dir }}"
    state: absent

- name: "Remove alertmanager storage file"
  ansible.builtin.file:
    path: "{{ alertmanager_storage_path }}"
    state: absent
  when: data_file.stat.exists

- name: Remove user 
  ansible.builtin.user:
    name: "{{ alertmanager_user }}"
    state: absent

- name: Remove SSL
  ansible.builtin.file:
    path: "/etc/alertmanager_ssl"
    state: absent
  when: ssl_folder.stat.exists

- name: Remove SSL client
  ansible.builtin.file:
    path: "/etc/alertmanager_ssl_client"
    state: absent
  when: ssl_client.stat.exists

  