all:
  hosts:
    node_exporter1:
      ansible_host: 10.15.14.115
    node_exporter2:
      ansible_host: 10.15.51.136
    node_exporter3:
      ansible_host: 10.15.0.168
    node_exporter4:
      ansible_host: 10.15.51.126
    blackbox_exporter1:
      ansible_host: 10.15.28.71
    thanos_query1:
      ansible_host: 10.15.42.186
    thanos_query2:
      ansible_host: 10.15.24.190
    thanos_query3:
      ansible_host: 10.15.5.25
    thanos_store1:
      ansible_host: 10.15.63.157
    thanos_store2:
      ansible_host: 10.15.44.23
    thanos_compactor1:
      ansible_host: 10.15.23.204
    thanos_rule1:
      ansible_host: 10.15.63.251
    prometheus1:
      ansible_host: 10.15.43.185
      replica: A
    prometheus2:
      ansible_host: 10.15.53.196
      replica: B
    prometheus3:
      ansible_host: 10.15.20.174
      replica: C
    alertmanager1:
      ansible_host: 10.15.49.147
      ansible_private_host: 10.15.49.147
      delay: 5
    alertmanager2:
      ansible_host: 10.15.13.180
      ansible_private_host: 10.15.13.180
      delay: 20
    alertmanager3:
      ansible_host: 10.15.62.247
      ansible_private_host: 10.15.62.247
      delay: 45
    grafana1:
      ansible_host: 10.15.15.246
    grafana2:
      ansible_host: 10.15.17.231
    ntp:
      ansible_host: 148.253.97.37
    minio1:
      ansible_host: 10.15.38.212
    haproxy_thanos_query1:
      ansible_host: 10.15.10.193
      mode: "tcp"
      option: "tcplog"
      listen: "thanos_query_passtrough"
      listen_option: "tcp-check"
      haproxy_servers:
      - { name: "query1", address: "10.15.42.186"}
      - { name: "query2", address: "10.15.24.190"}
      - { name: "query3", address: "10.15.5.25"}
      virtual_router_id: "51"
      keepalived_vip: "10.15.63.250"
      keepalived_priority: 100
    haproxy_thanos_query2:
      ansible_host: 10.15.34.141
      mode: "tcp"
      option: "tcplog"
      listen: "thanos_query_passtrough"
      listen_option: "tcp-check"
      haproxy_servers:
      - { name: "query1", address: "10.15.42.186"}
      - { name: "query2", address: "10.15.24.190"}
      - { name: "query3", address: "10.15.5.25"}
      virtual_router_id: "51"
      keepalived_vip: "10.15.63.250"
      keepalived_priority: 50
    haproxy_thanos_store1:
      ansible_host: 10.15.30.60
      mode: "tcp"
      option: "tcplog"
      listen: "thanos_store"
      listen_option: "tcp-check"
      haproxy_servers:
      - { name: "store1", address: "10.15.63.157"}
      - { name: "store2", address: "10.15.44.23"}
      virtual_router_id: "52"
      keepalived_vip: "10.15.63.249"
      keepalived_priority: 100
    haproxy_thanos_store2:
      ansible_host: 10.15.37.170
      mode: "tcp"
      option: "tcplog"
      listen: "thanos_store"
      listen_option: "tcp-check"
      haproxy_servers:
      - { name: "store1", address: "10.15.63.157"}
      - { name: "store2", address: "10.15.44.23"}
      virtual_router_id: "52"
      keepalived_vip: "10.15.63.249"
      keepalived_priority: 50

  children:
    blackbox:
      hosts:
        blackbox_exporter1:
    prometheus:
      hosts:
        prometheus1:
        prometheus2:
        prometheus3:
    alertmanagers:
      hosts:
        alertmanager1:
        alertmanager2:
        alertmanager3:
    grafana:
      hosts:
        grafana1:
        grafana2:
    thanos_query:
      hosts:
        thanos_query1:
        thanos_query2:
        thanos_query3:
    thanos_store:
      hosts:
        thanos_store1:
        thanos_store2:
    thanos_rule:
      hosts:
        thanos_rule1:
    thanos_compactor:
      hosts:
        thanos_compactor1:
    minio:
      hosts:
        minio1:
    haproxy:
      hosts:
        haproxy_thanos_query1:
        haproxy_thanos_query2:
        haproxy_thanos_store1:
        haproxy_thanos_store2:

