#SPDX-License-Identifier: MIT-0
---
# handlers file for install_node_exporter
- name: Restart node_exporter
  ansible.builtin.systemd_service:
    name: node_exporter.service
    state: restarted
    enabled: true
    daemon_reload: true
    force: false # Override existing symlinks