#SPDX-License-Identifier: MIT-0
---
# handlers file for haproxy_keepalived
- name: Restart haproxy
  ansible.builtin.systemd_service:
    name: haproxy
    state: restarted
    enabled: yes
    daemon_reload: yes


