#SPDX-License-Identifier: MIT-0
---
# defaults file for elasticsearch
es_version: "9.0.0"
es_archive_url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ es_version }}-linux-x86_64.tar.gz"
es_archive_checksum_url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ es_version }}-linux-x86_64.tar.gz.sha512"
es_install_dir: "/etc/elasticsearch"
es_user: elasticsearch
es_group: elasticsearch
es_heap_size: "1g"